export enum PerCode {
  PERMISSION_LIBRARY = 'PERMISSION_LIBRARY ',
  PERMISSION_PATIENT = 'PERMISSION_PATIENT ',
  PERMISSION_PASSWORD = 'PERMISSION_PASSWORD ',
  PERMISSION_DELETE = 'PERMISSION_DELETE ',
  PERMISSION_CALENDAR = 'PERMISSION_CALENDAR ',
  PERMISSION_BILLING = 'PERMISSION_BILLING ',
  PERMISSION_PAIEMENT = 'PERMISSION_PAIEMENT ',
  PERMISSION_ACCOUNTING = 'PERMISSION_ACCOUNTING ',
}
