import { AddressEntity } from 'src/entities/address.entity';
import { LettersEntity } from 'src/entities/letters.entity';
import { PaymentItemRes } from 'src/payment-schedule/response/payment.res';

export class DevisStd2InitRes {
  id_user: number;
  id_pdt: number;
  schemas: string;
  couleur: string;
  userPreferenceQuotationColor: string;
  identPrat: string;
  adressePrat: string;
  id_contact: number;
  nom_prenom_patient: string;
  adresse_pat: string;
  date_devis: string;
  date_acceptation: string;
  descriptions: string[];
  infosCompl: string;
  etatBucco: string;
  quotationSignaturePatient: string | null;
  quotationSignaturePraticien: string | null;
  paymentScheduleId: number;
  reference: string;
  doctorRpps: string;
  patientNumber: string;
  patientLastname: string;
  patientFirstname: string;
  patientBirthday: string;
  patientInsee: string;
  patientCivilityName: string;
  patientCivilityLongName: string;
  actes: DevisStd2ActesRes[];
  userSocialSecurityReimbursementRate?: number;
  userRateCharges?: number;
  userSignature?: string;
  addressEntity: AddressEntity;
  medical_entete_id: number;
  datedevisStd2: string;
  titredevisStd2: string;
  txch: number;
  userPreferenceQuotationDisplayTooltip: number;
  adresse_prat: string;
  civilite: string;
  tel: string;
  duree_devis: string;
  organisme: string;
  contrat: string;
  ref: string;
  dispo: string;
  dispo_desc: string;
  dateSql: string;
  paymentSchedule: PaymentItemRes;
  id_devisStd2_ligne: number;
  attachments: LettersEntity[];
  id_facture?: number;
  noFacture?: string;
  socialSecurityReimbursementRate?: number;
  details: DevisStd2ActesRes[];
  total_prixvente: number;
  total_prestation: number;
  total_charges: number;
  total_prixLigne: number;
  total_rss: number;
  total_nrss: number;
  total_roc: number;
  odontogramType: string;
  schemaActuel: string;
  schemaDevis: string;
  date_signature: string;
}

export class DevisStd2ActesRes {
  id_devisStd2_ligne?: number;
  typeLigne?: string;
  dateLigne?: string;
  dentsLigne?: string;
  descriptionLigne?: string;
  materiau?: string;
  cotation?: string;
  remboursable?: string;
  prixachat?: number;
  prixLigne?: number;
  tarif_secu?: number;
  rss?: number;
  roc?: number;
  library_act_id?: number;
  library_act_quantity_id?: number;
  nouveau?: boolean;
  prixvente?: number;
  round?: number;
  prestation?: number;
  charges?: number;
  nrss?: number;
}
