import { UserEntity } from 'src/entities/user.entity';

export class QuotationInitChampsRes {
  id_pdt?: number;
  id_devis?: number;
  txch?: number;
  ids_events?: string;
  last_event_id: number;
  tauxRemboursementSecu?: number;
  schemas?: string;
  details?: string;
  quotationSignaturePatient?: null;
  quotationSignaturePraticien?: null;
  hasCcamEnabled?: boolean;
  quotationMutualTitle?: string;
  ident_pat?: number;
  id_contact?: number;
  id_user?: number;
  ident_prat?: string;
  adressePrat?: string;
  userNumeroFacturant?: string;
  userRateCharges?: number;
  userSignature?: string;
  medicalHeaderIdentPratQuot?: string;
  periodOfValidity: number;
  quotationPlaceOfManufacture: number;
  quotationPlaceOfManufactureLabel: string;
  quotationWithSubcontracting: number;
  quotationPlaceOfSubcontracting: number;
  quotationPlaceOfSubcontractingLabel: string;
  userPreferenceQuotationDisplayOdontogram: string;
  userPreferenceQuotationDisplayDetails: string;
  userPreferenceQuotationDisplayNotice: number;
  reference: string;
  patientLastname: string;
  patientFirstname: string;
  patientCivilityName: string;
  nom_prenom_patient: string;
  INSEE: string;
  date_de_naissance_patient: string;
  tel: string;
  email: string;
  adresse_pat: string;
  quotationAmount: number;
  quotationPersonRepayment: number;
  quotationPersonAmount: number;
  actes: QuotationInitActeRes[];
  date_devis: string;
  duree_devis: string;
  organisme: string;
  contrat: string;
  ref: string;
  dispo: boolean;
  dispo_desc: string;
  description: string;
  date_acceptation: string;
  user: UserEntity;
  paymentScheduleId: number;
  patientNumber: number;
  patientBirthday: number;
  patientInsee: number;
  patientCivilityLongName: number;
  id_facture: number;
  noFacture: string;
  max_long_libelle: number;
  ar_details: QuotationInitActeRes[];
  max_long_localisation: number;
  total_prixvente: number;
  total_prestation: number;
  total_charges: number;
  total_honoraires: number;
  total_secuAmount: number;
  total_secuRepayment: number;
  total_mutualRepayment: number;
  total_mutualComplement: number;
  total_personAmount: number;
  total_remboursement: number;
  total_charges_patient: number;
  total_rss: number;
  total_nrss: number;
  total_roc: string;
  nb_lignes: number;
  nb_max_lignes_page1: number;
  nb_max_lignes_pageN: number;
  nb_lignes_annexe: number;
  nb_max_lignes_annexe_page1: number;
  nb_max_lignes_annexe_pageN: number;
  odontogramType: string;
  date_signature: string;
  initSchemas: odontogramStyleRes;
  currentSchemas: odontogramStyleRes;
  planSchemas: odontogramStyleRes;
}

export class odontogramStyleRes {
  [key: string]: string;
}

export class QuotationInitActeRes {
  id_devis_acte?: number;
  library_act_id?: number;
  library_act_quantity_id?: number;
  localisation?: string;
  libelle?: string;
  materiau?: string;
  cotation?: string;
  remboursable?: string;
  prixachat?: number;
  honoraires?: number;
  tarif_secu?: number;
  rss?: number;
  roc?: number | string;
  secuAmount?: number;
  secuRepayment?: number;
  mutualRepaymentType?: number;
  mutualRepaymentRate?: number;
  mutualRepayment?: number;
  mutualComplement?: number;
  personRepayment?: number;
  personAmount?: number;
  nouveau?: boolean;
  prixvente?: number;
  prestation?: number;
  charges?: number;
  nrss?: number;
  ngapKeyName?: string;
  ngapKeyUnitPrice?: number;
}
